#ifndef QTRESTWRAPPER_GLOBAL_H
#define QTRESTWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTRESTWRAPPER_LIBRARY)
#  define QTRESTWRAPPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTRESTWRAPPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTRESTWRAPPER_GLOBAL_H
